

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.commons.lang3.time.StopWatch;

public class Jobs {

	private List<String> jobs;
	private StopWatch stopWatch;
	
	public List<String> ContainsExact(String queryStr)  {
		stopWatch.reset();
		stopWatch.start();
		List<String> result = new ArrayList<String>();
		jobs.forEach(std -> {
			if (isMatched(queryStr, std)) {
				result.add(std);
			}
			
		});
		stopWatch.stop();
		System.out.println("ContainsExact time: " +stopWatch.getTime(TimeUnit.MILLISECONDS) + "ms" );
		return result;
	}
	
	private static boolean isMatched(String query, String text) {
        return text.toLowerCase().contains(query.toLowerCase());
    }
	
	public int size() {
		return jobs.size();
	}
	
	public Jobs() {
		stopWatch = new StopWatch();
		jobs = new ArrayList<String>();
		jobs.add("Aboriginal and Torres Strait Islander Education Worker");
		jobs.add("Aboriginal and Torres Strait Islander Education Worker");
		jobs.add("Aboriginal and Torres Strait Islander Health Worker");
		jobs.add("Accommodation and Hospitality Managers nec");
		jobs.add("Accountant (General)");
		jobs.add("Accounts Clerk");
		jobs.add("Actor");
		jobs.add("Actors, Dancers and Other Entertainers nec");
		jobs.add("Actuary");
		jobs.add("Acupuncturist");
		jobs.add("Admissions Clerk");
		jobs.add("Advertising and Public Relations Manager");
		jobs.add("Advertising Specialist");
		jobs.add("Aeronautical Engineer");
		jobs.add("Aeroplane Pilot");
		jobs.add("Aged or Disabled Carer");
		jobs.add("Agricultural and Horticultural Mobile Plant Operator");
		jobs.add("Agricultural Consultant");
		jobs.add("Agricultural Engineer");
		jobs.add("Agricultural Scientist");
		jobs.add("Agricultural Technician");
		jobs.add("Air Traffic Controller");
		jobs.add("Air Transport Professionals nec");
		jobs.add("Airconditioning and Mechanical Services Plumber");
		jobs.add("Airconditioning and Refrigeration Mechanic");
		jobs.add("Aircraft Baggage Handler and Airline Ground Crew");
		jobs.add("Aircraft Maintenance Engineer (Avionics)");
		jobs.add("Aircraft Maintenance Engineer (Mechanical)");
		jobs.add("Aircraft Maintenance Engineer (Structures)");
		jobs.add("Aircraft Refueller");
		jobs.add("Alarm, Security or Surveillance Monitor");
		jobs.add("Ambulance Officer");
		jobs.add("Amusement Centre Manager");
		jobs.add("Anaesthetic Technician");
		jobs.add("Anaesthetist");
		jobs.add("Analyst Programmer");
		jobs.add("Anatomist or Physiologist");
		jobs.add("Animal Attendants and Trainers nec");
		jobs.add("Antique Dealer");
		jobs.add("Apiarist");
		jobs.add("Apparel Cutter");
		jobs.add("Aquaculture Farmer");
		jobs.add("Aquaculture Worker");
		jobs.add("Arborist");
		jobs.add("Architect");
		jobs.add("Architectural Draftsperson");
		jobs.add("Archivist");
		jobs.add("Armoured Car Escort");
		jobs.add("Art Director (Film, Television or Stage)");
		jobs.add("Art Teacher (Private Tuition)");
		jobs.add("Artistic Director");
		jobs.add("Arts Administrator or Manager");
		jobs.add("Auctioneer");
		jobs.add("Audiologist");
		jobs.add("Author");
		jobs.add("Autoglazier");
		jobs.add("Automobile Drivers nec");
		jobs.add("Automotive Electrician");
		jobs.add("Backhoe Operator");
		jobs.add("Baker");
		jobs.add("Baking Factory Worker");
		jobs.add("Bank Worker");
		jobs.add("Bar Attendant");
		jobs.add("Bar Useful or Busser");
		jobs.add("Barista");
		jobs.add("Barrister");
		jobs.add("Beauty Therapist");
		jobs.add("Bed and Breakfast Operator");
		jobs.add("Beef Cattle Farm Worker");
		jobs.add("Beef Cattle Farmer");
		jobs.add("Betting Agency Counter Clerk");
		jobs.add("Betting Agency Manager");
		jobs.add("Betting Clerks nec");
		jobs.add("Bicycle Mechanic");
		jobs.add("Binder and Finisher");
		jobs.add("Biochemist");
		jobs.add("Biomedical Engineer");
		jobs.add("Biotechnologist");
		jobs.add("Blacksmith");
		jobs.add("Boarding Kennel or Cattery Operator");
		jobs.add("Boat Builder and Repairer");
		jobs.add("Boiler or Engine Operator");
		jobs.add("Book or Script Editor");
		jobs.add("Bookkeeper");
		jobs.add("Bookmaker");
		jobs.add("Bookmaker's Clerk");
		jobs.add("Botanist");
		jobs.add("Brewery Worker");
		jobs.add("Bricklayer");
		jobs.add("Broadcast Transmitter Operator");
		jobs.add("Builder's Labourer");
		jobs.add("Building and Engineering Technicians nec");
		jobs.add("Building Associate");
		jobs.add("Building Inspector");
		jobs.add("Building Insulation Installer");
		jobs.add("Bulk Materials Handling Plant Operator");
		jobs.add("Bulldozer Operator");
		jobs.add("Bungy Jump Master");
		jobs.add("Bus Driver");
		jobs.add("Business Broker");
		jobs.add("Business Machine Mechanic");
		jobs.add("Butcher or Smallgoods Maker");
		jobs.add("Cabinetmaker");
		jobs.add("Cabler (Data and Telecommunications)");
		jobs.add("Cafe or Restaurant Manager");
		jobs.add("Cafe Worker");
		jobs.add("Call or Contact Centre Manager");
		jobs.add("Call or Contact Centre Operator");
		jobs.add("Call or Contact Centre Team Leader");
		jobs.add("Camera Operator (Film, Television or Video)");
		jobs.add("Canvas Goods Maker");
		jobs.add("Car Detailer");
		jobs.add("Car Park Attendant");
		jobs.add("Caravan Park and Camping Ground Manager");
		jobs.add("Cardiac Technician");
		jobs.add("Cardiologist");
		jobs.add("Cardiothoracic Surgeon");
		jobs.add("Careers Counsellor");
		jobs.add("Caretaker");
		jobs.add("Carpenter");
		jobs.add("Carpenter and Joiner");
		jobs.add("Carpet Cleaner");
		jobs.add("Cartographer");
		jobs.add("Cash Van Salesperson");
		jobs.add("Cement and Concrete Plant Worker");
		jobs.add("Cement Production Plant Operator");
		jobs.add("Charter and Tour Bus Driver");
		jobs.add("Chauffeur");
		jobs.add("Checkout Operator");
		jobs.add("Chef");
		jobs.add("Chemical Engineer");
		jobs.add("Chemical Plant Operator");
		jobs.add("Chemical Plant Worker");
		jobs.add("Chemical Production Machine Operator");
		jobs.add("Chemist");
		jobs.add("Chemistry Technician");
		jobs.add("Chief Executive or Managing Director");
		jobs.add("Chief Information Officer");
		jobs.add("Child Care Centre Manager");
		jobs.add("Child Care Worker");
		jobs.add("Child or Youth Residential Care Assistant");
		jobs.add("Chiropractor");
		jobs.add("Chocolate Packer");
		jobs.add("Cinema or Theatre Manager");
		jobs.add("Civil Celebrant");
		jobs.add("Civil Engineer");
		jobs.add("Civil Engineering Draftsperson");
		jobs.add("Civil Engineering Technician");
		jobs.add("Classified Advertising Clerk");
		jobs.add("Clay Processing Factory Worker");
		jobs.add("Clay Products Machine Operator");
		jobs.add("Clay, Concrete, Glass and Stone Processing Machine Operators nec");
		jobs.add("Cleaners nec");
		jobs.add("Clerical and Administrative Workers nec");
		jobs.add("Clerical and Office Support Workers nec");
		jobs.add("Clerk of Court");
		jobs.add("Clinical Haematologist");
		jobs.add("Clinical Oncologist");
		jobs.add("Clinical Psychologist");
		jobs.add("Clothing Patternmaker");
		jobs.add("Clothing Trades Workers nec");
		jobs.add("Coding Clerk");
		jobs.add("Commercial Cleaner");
		jobs.add("Commercial Housekeeper");
		jobs.add("Commissioned Defence Force Officer");
		jobs.add("Commissioned Fire Officer");
		jobs.add("Commissioned Police Officer");
		jobs.add("Commodities Trader");
		jobs.add("Communications Operator");
		jobs.add("Community Arts Worker");
		jobs.add("Community Worker");
		jobs.add("Company Secretary");
		jobs.add("Complementary Health Therapists nec");
		jobs.add("Composer");
		jobs.add("Computer Network and Systems Engineer");
		jobs.add("Concrete Batching Plant Operator");
		jobs.add("Concrete Products Machine Operator");
		jobs.add("Concrete Pump Operator");
		jobs.add("Concreter");
		jobs.add("Confectionery Maker");
		jobs.add("Conference and Event Organiser");
		jobs.add("Conservation Officer");
		jobs.add("Conservator");
		jobs.add("Construction Estimator");
		jobs.add("Construction Project Manager");
		jobs.add("Construction Rigger");
		jobs.add("Container Filler");
		jobs.add("Contract Administrator");
		jobs.add("Conveyancer");
		jobs.add("Cook");
		jobs.add("Copywriter");
		jobs.add("Corporate General Manager");
		jobs.add("Corporate Services Manager");
		jobs.add("Corporate Treasurer");
		jobs.add("Cost Clerk");
		jobs.add("Cotton Grower");
		jobs.add("Counsellors nec");
		jobs.add("Courier");
		jobs.add("Court Bailiff or Sheriff (Aus) / Court Collections Officer (NZ)");
		jobs.add("Court Orderly (Aus) / Court Registry Officer (NZ)");
		jobs.add("Crane Chaser");
		jobs.add("Crane, Hoist or Lift Operator");
		jobs.add("Credit or Loans Officer");
		jobs.add("Crop Farm Workers nec");
		jobs.add("Crop Farmers nec");
		jobs.add("Crossing Supervisor");
		jobs.add("Crowd Controller");
		jobs.add("Customer Service Manager");
		jobs.add("Customs Officer");
		jobs.add("Dairy Cattle Farm Worker");
		jobs.add("Dairy Cattle Farmer");
		jobs.add("Dairy Products Maker");
		jobs.add("Dance Teacher (Private Tuition)");
		jobs.add("Dancer or Choreographer");
		jobs.add("Data Entry Operator");
		jobs.add("Database Administrator");
		jobs.add("Debt Collector");
		jobs.add("Deck Hand");
		jobs.add("Deer Farmer");
		jobs.add("Defence Force Member - Other Ranks");
		jobs.add("Defence Force Senior Officer");
		jobs.add("Delivery Driver");
		jobs.add("Dental Assistant");
		jobs.add("Dental Hygienist");
		jobs.add("Dental Prosthetist");
		jobs.add("Dental Specialist");
		jobs.add("Dental Technician");
		jobs.add("Dental Therapist");
		jobs.add("Dentist");
		jobs.add("Dermatologist");
		jobs.add("Despatching and Receiving Clerk");
		jobs.add("Detective");
		jobs.add("Developer Programmer");
		jobs.add("Diesel Motor Mechanic");
		jobs.add("Dietitian");
		jobs.add("Director (Film, Television, Radio or Stage)");
		jobs.add("Director of Photography");
		jobs.add("Disabilities Services Officer");
		jobs.add("Diver");
		jobs.add("Diversional Therapist");
		jobs.add("Diving Instructor (Open Water)");
		jobs.add("Dog Handler or Trainer");
		jobs.add("Dog or Horse Racing Official");
		jobs.add("Domestic Cleaner");
		jobs.add("Domestic Housekeeper");
		jobs.add("Doorperson or Luggage Porter");
		jobs.add("Door-to-door Salesperson");
		jobs.add("Drainage, Sewerage and Stormwater Labourer");
		jobs.add("Drainer (Aus) / Drainlayer (NZ)");
		jobs.add("Drama Teacher (Private Tuition)");
		jobs.add("Dressmaker or Tailor");
		jobs.add("Driller");
		jobs.add("Driller's Assistant");
		jobs.add("Driving Instructor");
		jobs.add("Drug and Alcohol Counsellor");
		jobs.add("Drycleaner");
		jobs.add("Early Childhood (Pre-primary School) Teacher");
		jobs.add("Earth Science Technician");
		jobs.add("Earthmoving Labourer");
		jobs.add("Earthmoving Plant Operator (General)");
		jobs.add("Economist");
		jobs.add("Education Adviser");
		jobs.add("Education Managers nec");
		jobs.add("Education Reviewer");
		jobs.add("Educational Psychologist");
		jobs.add("Electorate Officer");
		jobs.add("Electrical Engineer");
		jobs.add("Electrical Engineering Draftsperson");
		jobs.add("Electrical Engineering Technician");
		jobs.add("Electrical Linesworker (Aus) / Electrical Line Mechanic (NZ)");
		jobs.add("Electrical or Telecommunications Trades Assistant");
		jobs.add("Electrician (General)");
		jobs.add("Electrician (Special Class)");
		jobs.add("Electronic Engineering Draftsperson");
		jobs.add("Electronic Engineering Technician");
		jobs.add("Electronic Equipment Trades Worker");
		jobs.add("Electronic Instrument Trades Worker (General)");
		jobs.add("Electronic Instrument Trades Worker (Special Class)");
		jobs.add("Electronics Engineer");
		jobs.add("Electroplater");
		jobs.add("Emergency Medicine Specialist");
		jobs.add("Emergency Service Worker");
		jobs.add("Endocrinologist");
		jobs.add("Engineering Manager");
		jobs.add("Engineering Patternmaker");
		jobs.add("Engineering Production Systems Worker");
		jobs.add("Engineering Professionals nec");
		jobs.add("Engineering Technologist");
		jobs.add("Engraver");
		jobs.add("Enrolled Nurse");
		jobs.add("Entertainer or Variety Artist");
		jobs.add("Environmental Consultant");
		jobs.add("Environmental Engineer");
		jobs.add("Environmental Health Officer");
		jobs.add("Environmental Manager");
		jobs.add("Environmental Research Scientist");
		jobs.add("Environmental Scientists nec");
		jobs.add("Excavator Operator");
		jobs.add("Exhaust and Muffler Fitter");
		jobs.add("External Auditor");
		jobs.add("Fabric and Textile Factory Worker");
		jobs.add("Facilities Manager");
		jobs.add("Factory Process Workers nec");
		jobs.add("Faculty Head");
		jobs.add("Family and Marriage Counsellor");
		jobs.add("Family Day Care Worker");
		jobs.add("Family Support Worker");
		jobs.add("Farm, Forestry and Garden Workers nec");
		jobs.add("Farrier");
		jobs.add("Fashion Designer");
		jobs.add("Fast Food Cook");
		jobs.add("Fencer");
		jobs.add("Fibrous Plasterer");
		jobs.add("Filing or Registry Clerk");
		jobs.add("Film and Video Editor");
		jobs.add("Film, Television, Radio and Stage Directors nec");
		jobs.add("Finance Broker");
		jobs.add("Finance Manager");
		jobs.add("Financial Brokers nec");
		jobs.add("Financial Dealers nec");
		jobs.add("Financial Institution Branch Manager");
		jobs.add("Financial Investment Adviser");
		jobs.add("Financial Investment Manager");
		jobs.add("Financial Market Dealer");
		jobs.add("Fire Fighter");
		jobs.add("Fisheries Officer");
		jobs.add("Fishing Guide");
		jobs.add("Fishing Hand");
		jobs.add("Fitness Centre Manager");
		jobs.add("Fitness Instructor");
		jobs.add("Fitter (General)");
		jobs.add("Fitter and Turner");
		jobs.add("Fitter-Welder");
		jobs.add("Fleet Manager");
		jobs.add("Flight Attendant");
		jobs.add("Floor Finisher");
		jobs.add("Florist");
		jobs.add("Flower Grower");
		jobs.add("Flying Instructor");
		jobs.add("Food and Drink Factory Workers nec");
		jobs.add("Food Technologist");
		jobs.add("Food Trades Assistants nec");
		jobs.add("Footballer");
		jobs.add("Footwear Factory Worker");
		jobs.add("Footwear Production Machine Operator");
		jobs.add("Forester (Aus) / Forest Scientist (NZ)");
		jobs.add("Forestry Worker");
		jobs.add("Forklift Driver");
		jobs.add("Freight Handler (Rail or Road)");
		jobs.add("Fruit and Vegetable Factory Worker");
		jobs.add("Fruit and Vegetable Packer");
		jobs.add("Fruit or Nut Farm Worker");
		jobs.add("Fruit or Nut Grower");
		jobs.add("Fruit or Nut Picker");
		jobs.add("Funeral Director");
		jobs.add("Funeral Workers nec");
		jobs.add("Furniture Finisher");
		jobs.add("Furniture Removalist");
		jobs.add("Futures Trader");
		jobs.add("Gallery or Museum Curator");
		jobs.add("Gallery or Museum Guide");
		jobs.add("Gallery or Museum Technician");
		jobs.add("Gaming Worker");
		jobs.add("Garden Labourer");
		jobs.add("Gardener (General)");
		jobs.add("Gas or Petroleum Operator");
		jobs.add("Gasfitter");
		jobs.add("Gastroenterologist");
		jobs.add("General Clerk");
		jobs.add("General Medical Practitioner");
		jobs.add("Geologist");
		jobs.add("Geophysicist");
		jobs.add("Geotechnical Engineer");
		jobs.add("Glass Processing Worker");
		jobs.add("Glass Production Machine Operator");
		jobs.add("Glazier");
		jobs.add("Goat Farmer");
		jobs.add("Golfer");
		jobs.add("Grader Operator");
		jobs.add("Grain Mill Worker");
		jobs.add("Grain, Oilseed or Pasture Farm Worker (Aus) / Field Crop Farm Worker (NZ)");
		jobs.add("Grain, Oilseed or Pasture Grower (Aus) / Field Crop Grower (NZ)");
		jobs.add("Grape Grower");
		jobs.add("Graphic Designer");
		jobs.add("Graphic Pre-press Trades Worker");
		jobs.add("Greenkeeper");
		jobs.add("Gunsmith");
		jobs.add("Gymnastics Coach or Instructor");
		jobs.add("Hair or Beauty Salon Assistant");
		jobs.add("Hair or Beauty Salon Manager");
		jobs.add("Hairdresser");
		jobs.add("Handyperson");
		jobs.add("Hardware Technician");
		jobs.add("Health and Welfare Services Managers nec");
		jobs.add("Health Diagnostic and Promotion Professionals nec");
		jobs.add("Health Information Manager");
		jobs.add("Health Practice Manager");
		jobs.add("Health Promotion Officer");
		jobs.add("Helicopter Pilot");
		jobs.add("Hide and Skin Processing Machine Operator");
		jobs.add("Hide and Skin Processing Worker");
		jobs.add("Historian");
		jobs.add("Home Improvement Installer");
		jobs.add("Homoeopath");
		jobs.add("Horse Breeder");
		jobs.add("Horse Riding Coach or Instructor");
		jobs.add("Horse Trainer");
		jobs.add("Horticultural Nursery Assistant");
		jobs.add("Hospital Orderly");
		jobs.add("Hospital Pharmacist");
		jobs.add("Hospitality Workers nec");
		jobs.add("Hospitality, Retail and Service Managers nec");
		jobs.add("Hostel Parent");
		jobs.add("Hotel or Motel Manager");
		jobs.add("Hotel or Motel Receptionist");
		jobs.add("Hotel Service Manager");
		jobs.add("Human Resource Adviser");
		jobs.add("Human Resource Clerk");
		jobs.add("Human Resource Manager");
		jobs.add("Hunter-Trapper");
		jobs.add("Hunting Guide");
		jobs.add("ICT Account Manager");
		jobs.add("ICT Business Analyst");
		jobs.add("ICT Business Development Manager");
		jobs.add("ICT Customer Support Officer");
		jobs.add("ICT Managers nec");
		jobs.add("ICT Project Manager");
		jobs.add("ICT Quality Assurance Engineer");
		jobs.add("ICT Sales Assistant");
		jobs.add("ICT Sales Representative");
		jobs.add("ICT Security Specialist");
		jobs.add("ICT Support and Test Engineers nec");
		jobs.add("ICT Support Engineer");
		jobs.add("ICT Support Technicians nec");
		jobs.add("ICT Systems Test Engineer");
		jobs.add("ICT Trainer");
		jobs.add("Illustrator");
		jobs.add("Immigration Officer");
		jobs.add("Importer or Exporter");
		jobs.add("Import-Export Clerk");
		jobs.add("Industrial Designer");
		jobs.add("Industrial Engineer");
		jobs.add("Industrial Pharmacist");
		jobs.add("Industrial Spraypainter");
		jobs.add("Information and Organisation Professionals nec");
		jobs.add("Inquiry Clerk");
		jobs.add("Inspectors and Regulatory Officers nec");
		jobs.add("Insurance Agent");
		jobs.add("Insurance Broker");
		jobs.add("Insurance Consultant");
		jobs.add("Insurance Investigator");
		jobs.add("Insurance Loss Adjuster");
		jobs.add("Insurance Risk Surveyor");
		jobs.add("Integration Aide");
		jobs.add("Intelligence Officer");
		jobs.add("Intensive Care Ambulance Paramedic (Aus) / Ambulance Paramedic (NZ)");
		jobs.add("Intensive Care Specialist");
		jobs.add("Interior Decorator");
		jobs.add("Interior Designer");
		jobs.add("Internal Auditor");
		jobs.add("Internal Medicine Specialists nec");
		jobs.add("Interpreter");
		jobs.add("Ironer or Presser");
		jobs.add("Jeweller");
		jobs.add("Jewellery Designer");
		jobs.add("Jockey");
		jobs.add("Joiner");
		jobs.add("Journalists and Other Writers nec");
		jobs.add("Judge");
		jobs.add("Judicial and Other Legal Professionals nec");
		jobs.add("Kaiako Kohanga Reo (Maori Language Nest Teacher)");
		jobs.add("Kaiako Kura Kaupapa Maori (Maori-medium Primary School Teacher)");
		jobs.add("Kaiawhina (Hauora) (Maori Health Assistant)");
		jobs.add("Kaiawhina Kohanga Reo (Maori Language Nest Assistant)");
		jobs.add("Kaiawhina Kura Kaupapa Maori (Maori-medium School Assistant)");
		jobs.add("Kitchenhand");
		jobs.add("Knitting Machine Operator");
		jobs.add("Laboratory Manager");
		jobs.add("Labourers nec");
		jobs.add("Lagger");
		jobs.add("Land Economist");
		jobs.add("Landscape Architect");
		jobs.add("Landscape Gardener");
		jobs.add("Laundry Worker (General)");
		jobs.add("Law Clerk");
		jobs.add("Leaflet or Newspaper Deliverer");
		jobs.add("Leather Goods Maker");
		jobs.add("Legal Executive");
		jobs.add("Legal Secretary");
		jobs.add("Legislators nec");
		jobs.add("Liaison Officer");
		jobs.add("Librarian");
		jobs.add("Library Assistant");
		jobs.add("Library Technician");
		jobs.add("Licensed Club Manager");
		jobs.add("Life Science Technician");
		jobs.add("Life Scientist (General)");
		jobs.add("Life Scientists nec");
		jobs.add("Lifeguard");
		jobs.add("Lift Mechanic");
		jobs.add("Light Technician");
		jobs.add("Linemarker");
		jobs.add("Livestock Farm Workers nec");
		jobs.add("Livestock Farmers nec");
		jobs.add("Loader Operator");
		jobs.add("Local Government Legislator");
		jobs.add("Locksmith");
		jobs.add("Logging Assistant");
		jobs.add("Logging Plant Operator");
		jobs.add("Machine Operators nec");
		jobs.add("Machine Shorthand Reporter");
		jobs.add("Magistrate");
		jobs.add("Mail Clerk");
		jobs.add("Maintenance Planner");
		jobs.add("Make Up Artist");
		jobs.add("Management Accountant");
		jobs.add("Management Consultant");
		jobs.add("Manufacturer");
		jobs.add("Marine Biologist");
		jobs.add("Marine Transport Professionals nec");
		jobs.add("Market Research Analyst");
		jobs.add("Marketing Specialist");
		jobs.add("Massage Therapist");
		jobs.add("Master Fisher");
		jobs.add("Materials Engineer");
		jobs.add("Materials Recycler");
		jobs.add("Mathematician");
		jobs.add("Meat Boner and Slicer");
		jobs.add("Meat Inspector");
		jobs.add("Meat Packer");
		jobs.add("Meat Process Worker");
		jobs.add("Mechanical Engineer");
		jobs.add("Mechanical Engineering Draftsperson");
		jobs.add("Mechanical Engineering Technician");
		jobs.add("Mechanic's Assistant");
		jobs.add("Media Producer (excluding Video)");
		jobs.add("Medical Administrator (Aus) / Medical Superintendent (NZ)");
		jobs.add("Medical Diagnostic Radiographer");
		jobs.add("Medical Laboratory Scientist");
		jobs.add("Medical Laboratory Technician");
		jobs.add("Medical Practitioners nec");
		jobs.add("Medical Radiation Therapist");
		jobs.add("Medical Receptionist");
		jobs.add("Medical Technicians nec");
		jobs.add("Member of Parliament");
		jobs.add("Metal Casting Trades Worker");
		jobs.add("Metal Engineering Process Worker");
		jobs.add("Metal Fabricator");
		jobs.add("Metal Fitters and Machinists nec");
		jobs.add("Metal Machinist (First Class)");
		jobs.add("Metal Polisher");
		jobs.add("Metallurgical or Materials Technician");
		jobs.add("Metallurgist");
		jobs.add("Meteorologist");
		jobs.add("Meter Reader");
		jobs.add("Microbiologist");
		jobs.add("Middle School Teacher (Aus) / Intermediate School Teacher (NZ)");
		jobs.add("Midwife");
		jobs.add("Migration Agent (Aus) / Immigration Consultant (NZ)");
		jobs.add("Mine Deputy");
		jobs.add("Miner");
		jobs.add("Mining Engineer (excluding Petroleum)");
		jobs.add("Mining Support Worker");
		jobs.add("Minister of Religion");
		jobs.add("Mixed Crop and Livestock Farm Worker");
		jobs.add("Mixed Crop and Livestock Farmer");
		jobs.add("Mixed Crop Farmer");
		jobs.add("Mixed Livestock Farm Worker");
		jobs.add("Mixed Livestock Farmer");
		jobs.add("Mobile Plant Operators nec");
		jobs.add("Model");
		jobs.add("Money Market Clerk");
		jobs.add("Mothercraft Nurse");
		jobs.add("Motion Picture Projectionist");
		jobs.add("Motor Mechanic (General)");
		jobs.add("Motor Vehicle Licence Examiner");
		jobs.add("Motor Vehicle or Caravan Salesperson");
		jobs.add("Motor Vehicle Parts and Accessories Fitter (General)");
		jobs.add("Motor Vehicle Parts Interpreter (Aus) / Automotive Parts Salesperson (NZ)");
		jobs.add("Motorcycle Mechanic");
		jobs.add("Mountain or Glacier Guide");
		jobs.add("Multimedia Designer");
		jobs.add("Multimedia Specialist");
		jobs.add("Music Director");
		jobs.add("Music Professionals nec");
		jobs.add("Music Teacher (Private Tuition)");
		jobs.add("Musical Instrument Maker or Repairer");
		jobs.add("Musician (Instrumental)");
		jobs.add("Nanny");
		jobs.add("Natural and Physical Science Professionals nec");
		jobs.add("Natural Remedy Consultant");
		jobs.add("Naturopath");
		jobs.add("Naval Architect (Aus) / Marine Designer (NZ)");
		jobs.add("Network Administrator");
		jobs.add("Network Analyst");
		jobs.add("Neurologist");
		jobs.add("Neurosurgeon");
		jobs.add("Newspaper or Periodical Editor");
		jobs.add("Noxious Weeds and Pest Inspector");
		jobs.add("Nuclear Medicine Technologist");
		jobs.add("Nurse Educator");
		jobs.add("Nurse Manager");
		jobs.add("Nurse Practitioner");
		jobs.add("Nurse Researcher");
		jobs.add("Nurseryperson");
		jobs.add("Nursing Clinical Director");
		jobs.add("Nursing Support Worker");
		jobs.add("Obstetrician and Gynaecologist");
		jobs.add("Occupational Health and Safety Adviser");
		jobs.add("Occupational Therapist");
		jobs.add("Office Cashier");
		jobs.add("Office Manager");
		jobs.add("Operating Theatre Technician");
		jobs.add("Ophthalmologist");
		jobs.add("Optical Dispenser (Aus) / Dispensing Optician (NZ)");
		jobs.add("Optical Mechanic");
		jobs.add("Optometrist");
		jobs.add("Order Clerk");
		jobs.add("Organisation and Methods Analyst");
		jobs.add("Organisational Psychologist");
		jobs.add("Orthopaedic Surgeon");
		jobs.add("Orthoptist");
		jobs.add("Orthotist or Prosthetist");
		jobs.add("Osteopath");
		jobs.add("Other Sales Support Worker");
		jobs.add("Other Sports Coach or Instructor");
		jobs.add("Other Sports Official");
		jobs.add("Otorhinolaryngologist");
		jobs.add("Out of School Hours Care Worker");
		jobs.add("Outdoor Adventure Guides nec");
		jobs.add("Outdoor Adventure Instructor");
		jobs.add("Packers nec");
		jobs.add("Paediatric Surgeon");
		jobs.add("Paediatrician");
		jobs.add("Painter (Visual Arts)");
		jobs.add("Painting Trades Worker");
		jobs.add("Panelbeater");
		jobs.add("Paper and Pulp Mill Operator");
		jobs.add("Paper and Pulp Mill Worker");
		jobs.add("Paper Products Machine Operator");
		jobs.add("Park Ranger");
		jobs.add("Parking Inspector");
		jobs.add("Parole or Probation Officer");
		jobs.add("Passenger Coach Driver");
		jobs.add("Pastrycook");
		jobs.add("Pastrycook's Assistant");
		jobs.add("Patents Examiner");
		jobs.add("Pathologist");
		jobs.add("Paving and Surfacing Labourer");
		jobs.add("Paving Plant Operator");
		jobs.add("Payroll Clerk");
		jobs.add("Performing Arts Technicians nec");
		jobs.add("Personal Assistant");
		jobs.add("Personal Care Assistant");
		jobs.add("Personal Service Workers nec");
		jobs.add("Pest or Weed Controller");
		jobs.add("Pet Groomer");
		jobs.add("Petroleum Engineer");
		jobs.add("Pharmacy Sales Assistant");
		jobs.add("Pharmacy Technician");
		jobs.add("Photographer");
		jobs.add("Photographer's Assistant");
		jobs.add("Photographic Developer and Printer");
		jobs.add("Physicist");
		jobs.add("Physiotherapist");
		jobs.add("Picture Framer");
		jobs.add("Pig Farmer");
		jobs.add("Plastic and Reconstructive Surgeon");
		jobs.add("Plastic Cablemaking Machine Operator");
		jobs.add("Plastic Compounding and Reclamation Machine Operator");
		jobs.add("Plastics and Rubber Production Machine Operators nec");
		jobs.add("Plastics Fabricator or Welder");
		jobs.add("Plastics Factory Worker");
		jobs.add("Plastics Production Machine Operator (General)");
		jobs.add("Plastics Technician");
		jobs.add("Plumber (General)");
		jobs.add("Plumber's Assistant");
		jobs.add("Plumbing Inspector");
		jobs.add("Podiatrist");
		jobs.add("Police Officer");
		jobs.add("Policy Analyst");
		jobs.add("Policy and Planning Manager");
		jobs.add("Post Office Manager");
		jobs.add("Postal Delivery Officer");
		jobs.add("Postal Sorting Officer");
		jobs.add("Potter or Ceramic Artist");
		jobs.add("Pouako Kura Kaupapa Maori (Maori-medium Primary School Senior Teacher)");
		jobs.add("Poultry Farm Worker");
		jobs.add("Poultry Farmer");
		jobs.add("Poultry Process Worker");
		jobs.add("Power Generation Plant Operator");
		jobs.add("Practice Managers nec");
		jobs.add("Precision Instrument Maker and Repairer");
		jobs.add("Preschool Aide");
		jobs.add("Pressure Welder");
		jobs.add("Primary Health Organisation Manager");
		jobs.add("Primary Products Inspectors nec");
		jobs.add("Primary School Teacher");
		jobs.add("Print Journalist");
		jobs.add("Printer's Assistant");
		jobs.add("Printing Machinist");
		jobs.add("Printing Table Worker");
		jobs.add("Prison Officer");
		jobs.add("Private Investigator");
		jobs.add("Private Tutors and Teachers nec");
		jobs.add("Product Assembler");
		jobs.add("Product Examiner");
		jobs.add("Product Grader");
		jobs.add("Product Tester");
		jobs.add("Production Assistant (Film, Television, Radio or Stage)");
		jobs.add("Production Clerk");
		jobs.add("Production Manager (Forestry)");
		jobs.add("Production Manager (Manufacturing)");
		jobs.add("Production Manager (Mining)");
		jobs.add("Production or Plant Engineer");
		jobs.add("Program Director (Television or Radio)");
		jobs.add("Program or Project Administrator");
		jobs.add("Project Builder");
		jobs.add("Proof Reader");
		jobs.add("Property Manager");
		jobs.add("Psychiatrist");
		jobs.add("Psychologists nec");
		jobs.add("Psychotherapist");
		jobs.add("Public Relations Professional");
		jobs.add("Purchasing Officer");
		jobs.add("Quality Assurance Manager");
		jobs.add("Quantity Surveyor");
		jobs.add("Quarantine Officer");
		jobs.add("Radiator Fitter");
		jobs.add("Radio Despatcher");
		jobs.add("Radio Journalist");
		jobs.add("Radio Presenter");
		jobs.add("Radiocommunications Technician");
		jobs.add("Radiologist");
		jobs.add("Railway Signal Operator");
		jobs.add("Railway Station Manager");
		jobs.add("Railway Track Plant Operator");
		jobs.add("Railway Track Worker");
		jobs.add("Railways Assistant");
		jobs.add("Real Estate Agency Principal (Aus) / Real Estate Agency Licensee (NZ)");
		jobs.add("Real Estate Agent");
		jobs.add("Real Estate Representative");
		jobs.add("Receptionist (General)");
		jobs.add("Records Manager");
		jobs.add("Recreation Officer (Aus) / Recreation Coordinator (NZ)");
		jobs.add("Recruitment Consultant");
		jobs.add("Recycling or Rubbish Collector");
		jobs.add("Refuge Worker");
		jobs.add("Regional Education Manager");
		jobs.add("Registered Nurse (Aged Care)");
		jobs.add("Registered Nurse (Child and Family Health)");
		jobs.add("Registered Nurse (Community Health)");
		jobs.add("Registered Nurse (Critical Care and Emergency)");
		jobs.add("Registered Nurse (Developmental Disability)");
		jobs.add("Registered Nurse (Disability and Rehabilitation)");
		jobs.add("Registered Nurse (Medical Practice)");
		jobs.add("Registered Nurse (Medical)");
		jobs.add("Registered Nurse (Mental Health)");
		jobs.add("Registered Nurse (Perioperative)");
		jobs.add("Registered Nurse (Surgical)");
		jobs.add("Registered Nurses nec");
		jobs.add("Rehabilitation Counsellor");
		jobs.add("Reinforced Plastic and Composite Production Worker");
		jobs.add("Renal Medicine Specialist");
		jobs.add("Rental Salesperson");
		jobs.add("Research and Development Manager");
		jobs.add("Resident Medical Officer");
		jobs.add("Residential Care Officer");
		jobs.add("Retail Buyer");
		jobs.add("Retail Loss Prevention Officer");
		jobs.add("Retail Manager (General)");
		jobs.add("Retail Pharmacist");
		jobs.add("Retail Supervisor");
		jobs.add("Rheumatologist");
		jobs.add("Road Roller Operator");
		jobs.add("Roof Plumber");
		jobs.add("Roof Tiler");
		jobs.add("Rubber Factory Worker");
		jobs.add("Rubber Production Machine Operator");
		jobs.add("Safety Inspector");
		jobs.add("Sail Maker");
		jobs.add("Sales and Marketing Manager");
		jobs.add("Sales Assistant (General)");
		jobs.add("Sales Assistants and Salespersons nec");
		jobs.add("Sales Clerk");
		jobs.add("Sales Demonstrator");
		jobs.add("Sales Representative (Building and Plumbing Supplies)");
		jobs.add("Sales Representative (Business Services)");
		jobs.add("Sales Representative (Industrial Products)");
		jobs.add("Sales Representative (Medical and Pharmaceutical Products)");
		jobs.add("Sales Representative (Motor Vehicle Parts and Accessories)");
		jobs.add("Sales Representative (Personal and Household Goods)");
		jobs.add("Sales Representatives nec");
		jobs.add("Sand Blaster");
		jobs.add("Saw Maker and Repairer");
		jobs.add("Sawmill or Timber Yard Worker");
		jobs.add("Scaffolder");
		jobs.add("School Laboratory Technician");
		jobs.add("School Principal");
		jobs.add("Science Technicians nec");
		jobs.add("Screen Printer");
		jobs.add("Sculptor");
		jobs.add("Seafood Packer");
		jobs.add("Seafood Process Worker");
		jobs.add("Secondary School Teacher");
		jobs.add("Secretary (General)");
		jobs.add("Security Consultant");
		jobs.add("Security Officer");
		jobs.add("Security Officers and Guards nec");
		jobs.add("Senior Non-commissioned Defence Force Member");
		jobs.add("Service Station Attendant");
		jobs.add("Sewing Machinist");
		jobs.add("Sex Worker or Escort");
		jobs.add("Shearer");
		jobs.add("Sheep Farm Worker");
		jobs.add("Sheep Farmer");
		jobs.add("Sheetmetal Trades Worker");
		jobs.add("Shelf Filler");
		jobs.add("Ship's Engineer");
		jobs.add("Ship's Master");
		jobs.add("Ship's Officer");
		jobs.add("Ship's Surveyor");
		jobs.add("Shipwright");
		jobs.add("Shoemaker");
		jobs.add("Shot Firer");
		jobs.add("Sign Erector");
		jobs.add("Signwriter");
		jobs.add("Singer");
		jobs.add("Slaughterer");
		jobs.add("Small Engine Mechanic");
		jobs.add("Small Offset Printer");
		jobs.add("Snowsport Instructor");
		jobs.add("Social Professionals nec");
		jobs.add("Social Security Assessor");
		jobs.add("Social Worker");
		jobs.add("Software and Applications Programmers nec");
		jobs.add("Software Engineer");
		jobs.add("Solicitor");
		jobs.add("Solid Plasterer");
		jobs.add("Sonographer");
		jobs.add("Sound Technician");
		jobs.add("Special Education Teachers nec");
		jobs.add("Special Needs Teacher");
		jobs.add("Specialist Managers nec");
		jobs.add("Specialist Physician (General Medicine)");
		jobs.add("Speech Pathologist (Aus) / Speech Language Therapist (NZ)");
		jobs.add("Sports Administrator");
		jobs.add("Sports Centre Manager");
		jobs.add("Sports Development Officer");
		jobs.add("Sports Umpire");
		jobs.add("Sportspersons nec");
		jobs.add("Stablehand");
		jobs.add("Stage Manager");
		jobs.add("Stationary Plant Operators nec");
		jobs.add("Statistical Clerk");
		jobs.add("Statistician");
		jobs.add("Steel Fixer");
		jobs.add("Sterilisation Technician");
		jobs.add("Stock and Station Agent");
		jobs.add("Stock Clerk");
		jobs.add("Stockbroking Dealer");
		jobs.add("Stone Processing Machine Operator");
		jobs.add("Stonemason");
		jobs.add("Storeperson");
		jobs.add("Street Vendor");
		jobs.add("Streetsweeper Operator");
		jobs.add("Structural Engineer");
		jobs.add("Structural Steel Erector");
		jobs.add("Student Counsellor");
		jobs.add("Sugar Cane Grower");
		jobs.add("Sugar Mill Worker");
		jobs.add("Supply and Distribution Manager");
		jobs.add("Surgeon (General)");
		jobs.add("Survey Interviewer");
		jobs.add("Surveying or Cartographic Technician");
		jobs.add("Surveyor");
		jobs.add("Surveyor's Assistant");
		jobs.add("Swimming Coach or Instructor");
		jobs.add("Switchboard Operator");
		jobs.add("Systems Administrator");
		jobs.add("Systems Analyst");
		jobs.add("Tanker Driver");
		jobs.add("Taxation Accountant");
		jobs.add("Taxation Inspector");
		jobs.add("Taxi Driver");
		jobs.add("Teacher of English to Speakers of Other Languages");
		jobs.add("Teacher of the Hearing Impaired");
		jobs.add("Teacher of the Sight Impaired");
		jobs.add("Teachers' Aide");
		jobs.add("Technical Cable Jointer");
		jobs.add("Technical Director");
		jobs.add("Technical Sales Representatives nec");
		jobs.add("Technical Writer");
		jobs.add("Technicians and Trades Workers nec");
		jobs.add("Telecommunications Cable Jointer");
		jobs.add("Telecommunications Engineer");
		jobs.add("Telecommunications Field Engineer");
		jobs.add("Telecommunications Linesworker (Aus) / Telecommunications Line Mechanic (NZ)");
		jobs.add("Telecommunications Network Engineer");
		jobs.add("Telecommunications Network Planner");
		jobs.add("Telecommunications Technical Officer or Technologist");
		jobs.add("Telecommunications Technician");
		jobs.add("Telemarketer");
		jobs.add("Telephone Betting Clerk");
		jobs.add("Television Equipment Operator");
		jobs.add("Television Journalist");
		jobs.add("Television Presenter");
		jobs.add("Tennis Coach");
		jobs.add("Textile and Footwear Production Machine Operators nec");
		jobs.add("Textile Dyeing and Finishing Machine Operator");
		jobs.add("Textile, Clothing and Footwear Mechanic");
		jobs.add("Therapy Aide");
		jobs.add("Thoracic Medicine Specialist");
		jobs.add("Ticket Collector or Usher");
		jobs.add("Ticket Seller");
		jobs.add("Toolmaker");
		jobs.add("Tour Guide");
		jobs.add("Tourist Information Officer");
		jobs.add("Tow Truck Driver");
		jobs.add("Traditional Chinese Medicine Practitioner");
		jobs.add("Traditional Maori Health Practitioner");
		jobs.add("Train Controller");
		jobs.add("Train Driver");
		jobs.add("Train Examiner");
		jobs.add("Training and Development Professional");
		jobs.add("Tram Driver");
		jobs.add("Translator");
		jobs.add("Transport Company Manager");
		jobs.add("Transport Conductor");
		jobs.add("Transport Engineer");
		jobs.add("Transport Operations Inspector");
		jobs.add("Travel Agency Manager");
		jobs.add("Travel Attendants nec");
		jobs.add("Travel Consultant");
		jobs.add("Tree Faller");
		jobs.add("Trekking Guide");
		jobs.add("Tribunal Member");
		jobs.add("Trolley Collector");
		jobs.add("Truck Driver (General)");
		jobs.add("Truck Driver's Offsider");
		jobs.add("Trust Officer");
		jobs.add("Turf Grower");
		jobs.add("Tyre Fitter");
		jobs.add("University Lecturer");
		jobs.add("University Tutor");
		jobs.add("Upholsterer");
		jobs.add("Urban and Regional Planner");
		jobs.add("Urologist");
		jobs.add("Valuer");
		jobs.add("Vascular Surgeon");
		jobs.add("Vegetable Farm Worker (Aus) / Market Garden Worker (NZ)");
		jobs.add("Vegetable Grower (Aus) / Market Gardener (NZ)");
		jobs.add("Vegetable Picker");
		jobs.add("Vehicle Body Builder");
		jobs.add("Vehicle Painter");
		jobs.add("Vehicle Trimmer");
		jobs.add("Vending Machine Attendant");
		jobs.add("Veterinarian");
		jobs.add("Veterinary Nurse");
		jobs.add("Video Producer");
		jobs.add("Vineyard Worker");
		jobs.add("Visual Arts and Crafts Professionals nec");
		jobs.add("Visual Merchandiser");
		jobs.add("Vocational Education Teacher (Aus) / Polytechnic Teacher (NZ)");
		jobs.add("Waiter");
		jobs.add("Wall and Floor Tiler");
		jobs.add("Warehouse Administrator");
		jobs.add("Waste Water or Water Plant Operator");
		jobs.add("Watch and Clock Maker and Repairer");
		jobs.add("Water Inspector");
		jobs.add("Waterside Worker");
		jobs.add("Weaving Machine Operator");
		jobs.add("Web Administrator");
		jobs.add("Web Designer");
		jobs.add("Web Developer");
		jobs.add("Weighbridge Operator");
		jobs.add("Weight Loss Consultant");
		jobs.add("Welder (First Class) (Aus) / Welder (NZ)");
		jobs.add("Welfare Centre Manager");
		jobs.add("Welfare Worker");
		jobs.add("Whitewater Rafting Guide");
		jobs.add("Wholesaler");
		jobs.add("Window Cleaner");
		jobs.add("Wine Maker");
		jobs.add("Winery Cellar Hand");
		jobs.add("Wood and Wood Products Factory Worker");
		jobs.add("Wood Machinist");
		jobs.add("Wood Machinists and Other Wood Trades Workers nec");
		jobs.add("Wood Processing Machine Operator");
		jobs.add("Wood Turner");
		jobs.add("Wool Buyer");
		jobs.add("Wool Classer");
		jobs.add("Wool Handler");
		jobs.add("Word Processing Operator");
		jobs.add("Workplace Relations Adviser");
		jobs.add("Yarn Carding and Spinning Machine Operator");
		jobs.add("Youth Worker");
		jobs.add("Zookeeper");
		jobs.add("Zoologist");
		
		jobs.addAll(jobs);
		jobs.addAll(jobs);
		

	}
	
}
